### ISSUE TITLE
Überflüssiger BS bei gleicher Anzahl von Soll und Haben Konten bei "BS hinzufügen"

### ISSUE THREAD

**Issue by Xuanwu-shangdi** [Marek2/Buchfuehrungssoftware#18]
Es wird ein überflüssiger Buchungssatz erstellt mit Nullbetrag, wenn die Anzahl der Konten auf Soll- und Habenseite gleich sind.
![image](https://user-images.githubusercontent.com/29352430/28944915-b25fe05c-78a4-11e7-8689-ceb00468d98d.png)

**Comment by Xuanwu-shangdi** [comment]
Sophie klärt auf: Es kann immer nur n:1 oder 1:n sein.
Das heißt, sobald auf das Plus gedrückt wurde, muss es auf der anderen Seite verschwinden.

**Comment by Marek2** [comment]
Alte Werte werden nicht mehr übernommen

**Comment by Marek2** [comment]
Nur noch Buchungen mit n:1 oder 1:n möglich
