### ISSUE TITLE
Bei "Übersicht anzeigen" werden die BS zu einem Geschäftsfall nicht zusammengezogen

### ISSUE THREAD

**Issue by Xuanwu-shangdi** [Marek2/Buchfuehrungssoftware#19]
Bank an Verb, Ford wird zu Bank an Verb und Bank an Ford.
Lösung siehe Marc's Screenshots:

![image](https://user-images.githubusercontent.com/29352430/29090711-b9d4ee56-7c80-11e7-8080-6e3a323ac5e0.png)
![image](https://user-images.githubusercontent.com/29352430/29090720-bf2d66b2-7c80-11e7-82a9-5cf4e3ed4da9.png)

**Comment by Marek2** [comment]
schaffen wir eh nicht mehr
