### ISSUE TITLE
Kontenverwaltung - Konto hinzufügen: Keine Angabe von einem Anfangsbestand möglich

### ISSUE THREAD

**Issue by Marek2** [Marek2/Buchfuehrungssoftware#23]
Man kann keinen Anfangsbestand bei einem Bestandskonto Konto hinzufügen

![unbenannt](https://user-images.githubusercontent.com/11950014/29283625-d4110376-8127-11e7-9324-6e94e3c2c5c2.png)

Frag an @sophiels: Wenn ein Bestandskonto hinzugefügt wird, wie wird das mit dem Anfangsbestand gehandhabt? Wird, wenn es ein Aktivkonto ist der Anfangsbestand zum EK dazuaddiert und bei einem Passivkonto vom EK subtrahiert? Wenn man das nicht tut ist ja sonst die Summe der Bilanz nicht mehr korrekt.

**Comment by Xuanwu-shangdi** [comment]
Anfangsbestand wurde bewusst ausgelassen, da bei dem Menüpunkt nur Konten, die über das Jahr hinzukommen, hinzugefügt werden. Hätte es einen AB, dann müsste es bei Bilanz erstellen hinzugefügt werden sollen.

- so meine Auffassung -

**Comment by Xuanwu-shangdi** [comment]
Mit Sophie besprochen - keine AB sollen bei der Kontenverwaltung möglich sein
