### ISSUE TITLE
setExportNodes in GUIController macht Probleme

### ISSUE THREAD

**Issue by Xuanwu-shangdi** [Marek2/Buchfuehrungssoftware#25]
Die Methode musste im GUIController kommentiert werden. Sobald man auf die Kontenverwaltung ging, flogen die BS mit den Konten auf der Oberfläche raus. Ohne setExportNodes() ging es dann wieder normal (dafür dann kein PDF Export)

siehe: a26b67fd5cafda5e9574a1ebf594ccb5cd2a520b

**Comment by Marek2** [comment]
wurde entfernt
