### ISSUE TITLE
UE. FE keine Anfangsbestandänderung möglich

### ISSUE THREAD

**Issue by sophiels** [Marek2/Buchfuehrungssoftware#27]
wenn man UE, FE optional dazu wählt, werden sie nicht in der Übersicht angeziegt und es ist somit nicht möglich die Anfangsbestände zu ändern

**Comment by Marek2** [comment]
Wie wäre es, wenn man dem Benutzer sagt (also in Nutzerhandbuch schreibt), dass man den anfangsbestand dann selbst buchen muss? d.h. zb wenn man das ankreuzt man folgenden Buchungssatz durchführen soll:
UE an EK 50.000€

Das ist natürlich nicht sinn eines Anfangsbestandes, aber es wäre eine einfache Notlösung für das Problem
