### ISSUE TITLE
Menupunkt "Kontenverwaltung"

### ISSUE THREAD

**Issue by Marek2** [Marek2/Buchfuehrungssoftware#3]
- [x] Übersicht aller bisherigen Konten (keine Auswahl sondern es werden direkt alle angezeigt)
- [x] Hinzufügen eines neuen Kontos soll möglich sein
- [x] Export als PDF (Das würde ich dann Übernehmen, hab da schon eine gute Möglichkeit gefunden wie man das umsetzen kann ;) )

**Hier ist eine kleine Vorlage wie man das auf der GUI anordnen kann:**
![29-07-04-08](https://user-images.githubusercontent.com/11950014/28714508-051e8f7a-7394-11e7-85b1-36361581977b.png)

**Wichtig hierbei:**
- Vbox Alignment: left
- HBox Alignment: right
- TableView: guck dir mal an wie ich es in der Klasse BilanzErstellenController.java gemacht habe (Zeile 277-280)
- Konto hinzufügen: Dabei kannst du KontoBearbeiten.fxml benutzen (Bitte die fxml aber nicht bearbeiten^^; Falls du meinst da muss was geändert werden, kopiere die fxml und nenne die Kopie KontoHinzufuegen.fxml oder so und packe das unter richtigen Package :) )

**Comment by Marek2** [comment]
Vorerst unwichtig aber das brauche ich später für das Exportieren als Grundlage: https://stackoverflow.com/questions/29941817/save-javafx-scrollpane-content-to-pdf-file

**Comment by Xuanwu-shangdi** [comment]
@Marek2 warum bekomme ich die kontenListe nicht sauber übergeben (siehe Fehlermeldung)?

**Comment by Marek2** [comment]
@Xuanwu-shangdi kontoListe initialisieren :)

**Comment by Xuanwu-shangdi** [comment]
ToDo; Konten müssen hinzugefügt werden können (und zurückgegeben an die kontenverwaltung)
@Marek2 wie baut man die Fehlermeldungen ein?
