### ISSUE TITLE
Menüpunkt "Geschäftsfall > Übersicht anzeigen"

### ISSUE THREAD

**Issue by Marek2** [Marek2/Buchfuehrungssoftware#4]
- [x] Gesamte Übersicht anzeigen:
- Titel anzeigen
- Beschreibung anzeigen
- Wenn, BS vorhanden, dann ausgeben
- gut formatieren

- [x] Einzelne GF Übersicht anzeigen
 (nearly the same steps)

**Comment by Marek2** [comment]
@Xuanwu-shangdi das was mir aufgefallen ist:

1. Bei der FXML ist die Hierarchie folgendermaßen: ScrollPane -> AnchorPane -> VBox
    Mach lieber ScrollPane -> VBox weil so bindet sich die scrollpane an die vbox an und somit in seite 
    größe. du kannst sonst nicht scrollen^^
2. Damit bei längeren Beschreibungen der GF nicht einfach drei Punkte ganz links hinkommen, dem Label 
    mit der Beschreibung mit lb2.setWrapText(true); versehen, damit automatisch ein Umbruch erfolgt, wenn 
    er merkt es geht nicht weiter.

**Comment by Xuanwu-shangdi** [comment]
1. behoben
2. behoben :D 

@Marek2 Kannst du dir mal die Methode anschauen hasSatz(x, bsList)? --> ich versuche damit abzuprüfen, ob ein GF einen Buchungssatz hat (und ich brauche noch wieviele er hat..). Try catch ist da sicher keine optimale Lösung ^^. Eine Idee?

**Comment by Marek2** [comment]
@Xuanwu-shangdi Du hast bei mir keine Methode erstellt die so heißt^^

**Comment by Marek2** [comment]
Wozu übergibst du der Methode eigentlich Variablen? Brauchst du doch nicht^^ hast alle infos die du brauchst in dem Objekt. Versuchs mal damit:
`	public boolean hasSatz() {`
`		return !saetze.isEmpty();`
`	}`

**Comment by Xuanwu-shangdi** [comment]
@Marek2 TODO: Bitte schauen, ob du einverstanden bist und wenn ja, dann Issue schließen :)
