### ISSUE TITLE
Menüpunkt "Geschäftsfall > Neuer Buchungssatz"

### ISSUE THREAD

**Issue by Marek2** [Marek2/Buchfuehrungssoftware#6]
- [x] GUI: FXML und Controller impl.
- [x] Multiple Buchungssätze impl.
- [x] Buchungssätze an Geschäftsfall anbinden
- [x] Anzeige auf der GUI an der neuen "Situation" anpassen
- [x] An die Kontenverwaltung übergeben
- [x] Klasse MultiMap, die wie Map ist nur mehrere gleiche Keys beinhalten kann
- [x] Exceptionhandling
- [x] Das Fenster soll neu laden wenn auf "Buchungssatz hinzufügen" geklickt wird

**Comment by Marek2** [comment]
Zum Exceptionhandling:

- [ ] GF wird nicht angegeben
- [ ] keine Konten werden angegeben

**Comment by Xuanwu-shangdi** [comment]
- [ ] WrapText bei dem Titel des BS in einem Konto (wird bisher auch mit ... abgekürzt bei hohen Beträgen)

**Comment by Marek2** [comment]
@Xuanwu-shangdi Das ist eine schlechte Idee^^ damit geht das Format der Konten kaputt^^ Es würde dann so aussehen, wenn man z.B. zwei Sachen wie Bank 500.000€ und Kasse 400€ hat:
____________________________________
1. Bank   500.0   |
2. Kasse  00€     |
               400€   |
